### ISSUE TITLE
Beta versions of the compiler support could be improved

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/setup-ocaml#232]
With the following workflow file: https://github.com/ocaml/merlin/blob/56e0601ad40995421ae9e3537158af30559fb65f/.github/workflows/main.yml
```
 ocaml-compiler:
          - 4.13.0~beta1
```
Is not understood as a valid compiler version and will instead expect it to be a package name, which makes opam fail with:
```
> Install OCaml
  /opt/hostedtoolcache/opam/2.0.9/x86_64/opam switch create . --no-install --packages 4.13.0~beta1
  opam: option `--packages': invalid element in list (`4.13.0~beta1'): Invalid
        character in package name "4.13.0~beta1"
  am switch [OPTION]... [COMMAND] [ARG]...
  Try `opam switch --help' or `opam --help' for more information.
  Error: The process '/opt/hostedtoolcache/opam/2.0.9/x86_64/opam' failed with exit code 2
```

This is a valid version string for opam and expliciting `ocaml-base-compiler.4.13.0~beta1` shouldn't be required.

**Comment by voodoos** [comment]
And using `ocaml-base-compiler.4.13.0~beta1` the result is:
```
   /opt/hostedtoolcache/opam/2.0.9/x86_64/opam switch create . --no-install --packages ocaml-base-compiler.4.13.0~beta1
  [ERROR] Could not resolve set of base packages:
          The following dependencies couldn't be met:
            - ocaml-base-compiler → ocaml-beta
                unmet availability conditions: enable-ocaml-beta-repository
                ```

**Comment by dra27** [comment]
@voodoos - you need to add the ocaml-beta-repository explicitly, then that should work

**Comment by dra27** [comment]
I don’t think it should be extended to recognise that version string - the input is it intended to be an opam package version, but access to betas could definitely be improved, perhaps more along the lines of:

```
ocaml-compiler: 4.13.x
enable-beta-compilers: true
```

or some such. The main thing would be not specify the alpha, beta or rc number

**Comment by kit-ty-kate** [comment]
I totally agree. Well in the first place I was expecting setup-ocaml to use opam 2.1 so having a `enable-beta-compilers` field shouldn't be needed, but since it doesn't i guess this is one way to do it, though I think `ocaml-beta-repository` should always be set in CI with opam 2.0 in my opinion, that would take care of everything automatically be it on opam 2.0 or 2.1

**Comment by voodoos** [comment]
For the record here is the configuration that works for us:

```yaml
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - ocaml-base-compiler.4.13.0~beta1
        
    runs-on: ${{ matrix.os }}

    steps:
      - ...

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          # Version of the OCaml compiler to initialise
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            beta: https://github.com/ocaml/ocaml-beta-repository.git
```
