### ISSUE TITLE
`ocaml-variants.5.0.0+trunk` fails at `ocaml-depext` install step

### ISSUE THREAD

**Issue by dhil** [ocaml/setup-ocaml#391]
I have recently tried to setup a CI for a small project that uses OCaml 5.0.0+trunk, however, `setup-ocaml` fails to run properly. Specifically it fails at the install `ocaml-depext` step.

It seems to fail rather bizarrely because it cannot find `String.capitalize`, although that function still appears to be part of the `String` interface.
```
  # File "cmdliner/src/cmdliner.ml", line 427, characters 15-32:
  # 427 |     let prog = String.capitalize (fst ei.main).name in
  #                      ^^^^^^^^^^^^^^^^^
  # Error: Unbound value String.capitalize
```

The relevant bits of the [Action job definition](https://github.com/dhil/ocaml-multicont/blob/master/.github/workflows/default.yml) looks like
```yaml
 examples:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        ocaml-compiler:
          - ocaml-variants.5.00.0+trunk

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext: false
```

I wonder whether I need to use some special configuration options when using the trunk compiler variant?

The complete CI log https://github.com/dhil/ocaml-multicont/runs/4795657932?check_suite_focus=true.
