### ISSUE TITLE
Document usage of dependabot for keeping GH Action up to date.

### ISSUE THREAD

**Issue by tmcgilchrist** [ocaml/setup-ocaml#442]
It would be useful to point people to a simplified dependabot configuration to keep the setup-ocaml action up to date.
Bonus points for the project it keeps everyone up to date with minimal fuss.

For example
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" 
```
in a file under .github/dependabot.yml in your project will check monthly for newer versions of GH actions. Creating a PR updating the configuration if you do.
