### ISSUE TITLE
depext issues

### ISSUE THREAD

**Issue by hannesm** [ocaml/setup-ocaml#632]
I can see that opam 2.1 is installed by the setup-ocaml action:

```
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam --version
2.1.3
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam depext --version
1.2.1
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam exec -- ocaml -version
The OCaml toplevel, version 4.14.0
```

But somehow (and I don't understand how) there's a bunch of environment variables embedded:
```
  env:
    OPAMCLI: 2.0
    OPAMCOLOR: always
    OPAMERRLOGLEN: 0
    OPAMJOBS: 2
    OPAMPRECISETRACKING: 1
    OPAMSOLVERTIMEOUT: 1000
    OPAMVERBOSE: false
    OPAMYES: 1
```

Which make opam unnecessarily hard to use: `--confirm-level=always` is not supported (since `OPAMCLI` is set to 2.0), the depext has to be dealt with manually (opam depext <my-packages>).

Is there any way to use opam 2.1 features with this "setup-ocaml" action? Thanks a lot :)
