### ISSUE TITLE
Bad checksums?

### ISSUE THREAD

**Issue by rossberg** [ocaml/setup-ocaml#640]
All of a sudden , I'm seeing checksum errors when setting up OCaml in CI. Example log:
```
[...]
##[group]Install OCaml
[command]/opt/hostedtoolcache/opam/2.1.4/x86_64/opam switch create . --no-install --packages ocaml-base-compiler.4.13.1

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "4.13.1"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  5/21: [ocaml-base-compiler.4.13.1: http]
Processing  6/21: [ocaml-base-compiler.4.13.1: http]
Processing  7/21: [ocaml-base-compiler.4.13.1: http]
Processing  8/21: [ocaml-base-compiler.4.13.1: http]
Processing  9/21: [ocaml-base-compiler.4.13.1: http]
Processing 10/21: [ocaml-base-compiler.4.13.1: http]
Processing 11/21: [ocaml-base-compiler.4.13.1: http]
∗ installed base-bigarray.base
Processing 12/21: [ocaml-base-compiler.4.13.1: http]
∗ installed base-threads.base
Processing 13/21: [ocaml-base-compiler.4.13.1: http]
* Installed base-unix.base
Processing 14/21: [ocaml-base-compiler.4.13.1: http]
∗ installed ocaml-options-vanilla.1
Processing 15/21: [ocaml-base-compiler.4.13.1: http]
[ERROR] Failed to get sources of ocaml-base-compiler.4.13.1: Bad checksum

#=== ERROR while fetching sources for ocaml-base-compiler.4.13.1 ==============#
OpamSolution.Fetch_fail("https://github.com/ocaml/ocaml/archive/4.13.1.tar.gz (Bad checksum, expected sha256=194c7988cc1fd1c64f53f32f2f7551e5309e44d914d6efc7e2e4d002296aeac4)")
```

The job is this:
```
jobs:
  ref-interpreter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
      - run: opam install --yes ocamlbuild.0.14.0
      - run: cd interpreter && opam exec make all
```
It fails in the "Setup OCaml" step.

Any idea what could be causing this?
