### ISSUE TITLE
OCaml 5.x not found in some OS distributions

### ISSUE THREAD

**Issue by liyishuai** [ocaml/setup-ocaml#664]
https://github.com/liyishuai/cppo/actions/runs/5077685965 (macOS jobs queued as of now):
> No OCaml base compiler packages matched the version 5.2.x in the opam-repository.

| ocaml-version | ubuntu-latest | windows-latest | macos-latest |
|---|---|---|---|
| 5.0.x | OK | not found | (queued) |
| 5.1.x | not found | not found | (queued) |
| 5.2.x | not found | not found | (queued) |

**Comment by smorimoto** [comment]
Right now, we are still railing on top of the old non-native Windows support until opam 2.2 is released.

https://github.com/ocaml/setup-ocaml/blob/df82ae6bd3aad42c88dff020d3fab98ef5a2c668/packages/setup-ocaml/src/constants.ts#L77-L80

That means they don't use opam-repository, so technically they will use different packages. (This will probably be resolved in the next few weeks with the release of opam 2.2.)

https://github.com/ocaml/opam/milestone/34

5.1+ versions are still not stable in the first place, so you have to add a repository to unlock them.
See below for details on how to do it.

```yml
- name: Set-up OCaml ${{ matrix.ocaml-compiler }}
  uses: ocaml/setup-ocaml@v2
  with:
    ocaml-compiler: ${{ matrix.ocaml-compiler }}
    opam-repositories: |
      beta: https://github.com/ocaml/ocaml-beta-repository.git
      default: https://github.com/ocaml/opam-repository.git
```

https://github.com/ocaml/setup-ocaml/blob/df82ae6bd3aad42c88dff020d3fab98ef5a2c668/.github/workflows/workflow.yml#L75-L79
