### ISSUE TITLE
README should document cygwin interaction on Windows

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#71]
IMHO, the readme should document the answers to the following questions:
If I want to use cygwin and setup-ocaml on Windows, what's the workflow?  In particular:
  - Do I install cygwin separately, e.g., with egor-tensin/setup-cygwin?
  - If so, does it matter whether I do it before or after setup-ocaml?
  - If not, how do I get additional cygwin packages installed?
  - If not, where do I find the path to cygwin's bash?

**Comment by dra27** [comment]
Quoting [the README](https://github.com/avsm/setup-ocaml#action): “**Windows**: Installs Cygwin”!

It would be worth adding a sentence noting that `%CYGWIN_ROOT%` contains the location of the Cygwin installation and `setup-x86_64.exe` is dropped inside it.

The expected mechanism for installing additional packages would be to list them as depexts in your repository’s opam files and allow `opam depext` to install them.

FWIW, the intention of the action is to allow executing `opam exec --` so manipulating/using the Cygwin installation is outside its scope.

**Comment by JasonGross** [comment]
> FWIW, the intention of the action is to allow executing `opam exec --` so manipulating/using the Cygwin installation is outside its scope.

Unfortunately, if I install cygwin with, for example, egor-tensin/setup-cygwin@v1, then that cygwin is incapable of finding `opam`.  For example, with
```yaml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v1
      - name: Set up OCaml
        uses: avsm/setup-ocaml@v1.1.10
        with:
          ocaml-version: 4.11.1
      - run: opam list
        if: always()
      - run: opam list
        shell: bash
        if: always()
```
The first `opam list` succeeds, but the second fails with
```
Run opam list
  opam list
  shell: C:\tools\cygwin\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    CYGWIN: winsymlinks:nativestrict
    OPAMJOBS: 4
    OPAMYES: 1
    CYGWIN_ROOT: D:\cygwin
D:\a\_temp\cfa6db88-6f1d-478f-b0ae-492d60247548.sh: line 1: opam: command not found
Error: Process completed with exit code 127.
```
So it's not clear how to execute `opam exec --` when running scripts on Windows in Cygwin bash, and the interaction is not so orthogonal.

**Comment by dra27** [comment]
I'm not yet clear what you're trying to achieve - why are you wanting to set-up Cygwin separately?

**Comment by JasonGross** [comment]
There are some dependencies of the CI which are neither build dependencies nor runtime dependencies.  For example, I use a python script to analyze and present the build logs in a nice way on the CI, but this is not needed nor wanted when doing `opam install` of the code.  So I need a way to install a python accessible from bash.  I guess you're suggesting that I do this by invoking `%CYGWIN_ROOT%\setup_x86_64.exe`?  (I guess alternatively I could use the setup-python action.)

I'll also note that `shell: bash` doesn't ever seem to give OCaml's bash shell; if I have just the setup-ocaml action, then I `bash` seems to mean `C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}`...

**Comment by dra27** [comment]
You _could_ still install the CI dependencies using an opam file - you simply need an opam file in your repo containing the required depext statements and then pin it as part of your workflow. The old CI scripts [for Travis](https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-opam.sh#L28) do exactly that for the support package used to run that pipeline.

Assuming that setup-python installs Python for Windows, that may be a better bet - Cygwin brings its own complexities to the table!

At the moment, yes, additional packages would be installed by calling that setup program directly. However, all three runners call a package manager (`apt`, `brew` or Cygwin setup), so it would certainly be a welcome patch to have an input variable specifying additional OS packages to install (with it obviously being the workflow's job to ensure that the matrix gives the correct names for each platform!) which get added to the action's own call to the package manager.

The `shell: bash` part is intentional, yes - providing a Cygwin installation is outside the scope of the action, it just happens to include one. You either need to alter `PATH` first to put `%CYGWIN_ROOT%` as the wrapper does:
https://github.com/avsm/setup-ocaml/blob/db99006780235d1949350b5038e1a7eb1b0117d7/src/opam.cmd#L3-L4
or give a fully qualified path in `shell: `

FWIW, the roadmap for Windows opam eventually hides the Cygwin installation completely, but that's quite a way off at the moment!

**Comment by JasonGross** [comment]
> Assuming that setup-python installs Python for Windows, that may be a better bet - Cygwin brings its own complexities to the table!

This does not seem to work well, if I do
```
    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1.1.10
      with:
        ocaml-version: 4.11.1
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
    - run: |
        opam install opam-depext
      env:
        OPAMYES: "true"
      shell: "%CYGWIN_ROOT%/bin/bash.exe --noprofile --norc -eo pipefail {0}"
```
I get
```
Error: Could not find a part of the path 'C:\hostedtoolcache\windows\Python\3.9.4\x64\Scripts\%CYGWIN_ROOT%\bin'.
```
See https://github.com/mit-plv/fiat-crypto/runs/2513240566?check_suite_focus=true#step:6:5
