### ISSUE TITLE
Action should support new packages on windows out of the box

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#720]
I think the default on Windows should be
```
with:
  opam-repositories: |
    opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
    default: https://github.com/ocaml/opam-repository.git
```
so that we don't need to handle Windows and other OSs separately in, e.g., https://github.com/mit-plv/fiat-crypto/blob/b255107aa62c571ca0ec728c5cff5aae7723fa15/.github/workflows/coq-opam-package.yml#L22-L60
