### ISSUE TITLE
lint-doc lint-fmt neglect working-directory change

### ISSUE THREAD

**Issue by panyuewh** [ocaml/setup-ocaml#760]
My repo has following structure and the OCaml project is located in a sub-directory
```
./
  binding-Julia/
  binding-OCaml/
    .ocamlformat
    dune-project
    ...
  ...

```
I have configure the default value for lint-fmt job in workflow.yml, following the spec https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs. However, it seems lint-fmt@v2 neglect the change of default value of working-directory. Same for lint-doc. 

```
jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./binding-OCaml
    steps:
```
