### ISSUE TITLE
Can't use setup-ocaml@v2 with OCaml 5.2.0~beta2

### ISSUE THREAD

**Issue by aryx** [ocaml/setup-ocaml#778]
Here is an example of failure:
https://github.com/semgrep/semgrep/actions/runs/8725124955/job/23937327085?pr=10119

the workflow file is
```
# AUTOGENERATED FROM build-test-core-x86-ocaml5.jsonnet DO NOT MODIFY
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.2.0~beta2
      - env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
        name: Set GHA cache for OPAM in _opam
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-opam-deps-5.2.0~beta2-_opam-${{ hashFiles('semgrep.opam') }}
          path: _opam
      - name: Install semgrep dependencies
        run: |
          eval $(opam env)
          sudo make install-deps-UBUNTU-for-semgrep-core
          make install-deps-for-semgrep-core
      - name: Build semgrep
        run: |
          eval $(opam env)
          make
      - name: Test semgrep
        run: |
          echo TODO
name: build-test-core-x86-ocaml5
on:
  pull_request: null
  push:
    branches:
      - develop
  workflow_dispatch: null

```

and the error in GHA:
![image](https://github.com/ocaml/setup-ocaml/assets/332336/aaa8ad38-9c05-408c-ad4b-1448350d54c7)
