### ISSUE TITLE
Windows setup: OPAM package not found

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/setup-ocaml#802]
I'm trying to use setup-ocaml to prepare a Windows configuration with OCaml 4.14.2 and Coq 8.17.1.  (Workflow file below.)  At the `opam install` stage, I get
```
Run opam install -j4 coq=8.17.1 menhir
[ERROR] Package coq has no version 8.17.1.
```
I'm positive that the OPAM Coq package has a 8.17.1 version (https://opam.ocaml.org/packages/coq/coq.8.17.1/).

What's going on?  Is the Windows configuration of this action using a non-standard OPAM repository?

Generally speaking I could use more details on which of the 5 OCaml Windows versions is used, which version of OPAM, which repository is used, etc.  Thanks!

Relevant part of the workflow:
```
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14.2"
      - name: OPAM dependencies
        run: opam install -j4 coq=8.17.1 menhir
```
Full GHA error report:
```
Run opam install -j4 coq=8.17.1 menhir
  opam install -j4 coq=8.17.1 menhir
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    target: x86_64
    os: windows
    jobs: 4
    OPAMCLI: 2.0
    OPAMCOLOR: always
    OPAMERRLOGLEN: 0
    OPAMJOBS: 2
    OPAMPRECISETRACKING: 1
    OPAMSOLVERTIMEOUT: 1000
    OPAMYES: 1
    OPAMROOT: D:\.opam
    HOME: C:\Users\runneradmin
    MSYS: winsymlinks:native
    CYGWIN: winsymlinks:native
    CYGWIN_ROOT: D:\cygwin
    CYGWIN_ROOT_BIN: D:\cygwin\bin
    CYGWIN_ROOT_WRAPPERBIN: D:\cygwin\wrapperbin
    CLICOLOR_FORCE: 1
[ERROR] Package coq has no version 8.17.1.
Error: Process completed with exit code 1.
```
