### ISSUE TITLE
The action recompiles OCaml everytime

### ISSUE THREAD

**Issue by francoisthire** [ocaml/setup-ocaml#811]
I used the example provided here, and everytime the action is run, it recompiles OCaml:

![image](https://github.com/ocaml/setup-ocaml/assets/2529963/efee2c33-dced-4733-8bff-3defed8ae843)

I wonder why? It wants to install `host-arch-x86_64` and `host-system-other` for some reason.

The `build.yml` I am using is as follows:

```yml
name: build
run-name: Build project
on: [push]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: write
  
jobs:
  build_matrix:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        ocaml-compiler: [
            # OCaml LTS version
            ocaml.4.14.2,
            # ocaml.5.0.0,
            # ocaml.5.1.0
          ]
    steps:
      - uses: actions/checkout@v4
      - name: setting up opam...
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        run: |
          opam install . --deps-only -t
      - name: Build project
        run: |
          eval $(opam env)
          dune build .
      - name: Test
        run: |
          eval $(opam env)
          dune exec test/main.exe -- --keep-going
      - name: Build documentation
        run: |
          eval $(opam env)
          opam install odoc
          dune build @doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/default/_doc/_html
```
