### ISSUE TITLE
Syntax for opam-repositories ?

### ISSUE THREAD

**Issue by fblanqui** [ocaml/setup-ocaml#813]
Hello. Could you please describe the syntax to use for opam-repositories, and give some examples?

**Comment by smorimoto** [comment]
It's expected to be the YAML mapping: https://yaml.org/spec/1.2.2/#nodes

```yaml
default: https://github.com/ocaml/opam-repository.git
```

or

```yaml
default: https://github.com/ocaml/opam-repository.git
beta: https://github.com/ocaml/ocaml-beta-repository.git
```

**Comment by fblanqui** [comment]
I see. Thank you. Is https://github.com/ocaml/opam-repository.git used even if not mentioned?

**Comment by fblanqui** [comment]
Note that in README.md it is written that it is of type string, which is a little confusing (I'm not super familiar with yaml).

**Comment by smorimoto** [comment]
> Is https://github.com/ocaml/opam-repository.git used even if not mentioned?

Yes, it's the default opam repository.

> Note that in README.md it is written that it is of type string, which is a little confusing (I'm not super familiar with yaml).

Although it's actually technically just string, because of GHA restrictions, its actual content is the YAML mapping...

**Comment by fblanqui** [comment]
Sorry but I still have some syntactic issue: "A mapping was not expected". What is wrong with the following?
```
      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
          opam-repositories:
            default: https://github.com/ocaml/opam-repository.git
            beta: https://github.com/ocaml/ocaml-beta-repository.git
```
