### ISSUE TITLE
Opam caching doesn't work? 

### ISSUE THREAD

**Issue by rusty-key** [ocaml/setup-ocaml#831]
Hello! I am confused about opam caching in the action, I hope you can clarify how it supposed to work. 

I am currently using my opam caching using `actions/cache`, which works fine. However, I noticed that `ocaml/setup-ocaml` also restores some opam cache: 
```
Retrieve the opam cache
  Cache Size: ~134 MB (140693824 B)
  /usr/bin/tar -xf /home/runner/work/_temp/28ed0a57-bbe7-4c7d-a2c2-802adb7bad63/cache.tzst -P -C /home/runner/work/mapmap/mapmap --use-compress-program unzstd
  Received 140693824 of 140693824 (100.0%), 134.0 MBs/sec
  Cache restored successfully
  Cache restored from key: v1-setup-ocaml-opam-2.2.0-sandbox-linux-x86_64-ocaml_base_compiler_5_01_1
```

But when I remove `actions/cache` steps, I can see that whatever is restored with `ocaml/setup-ocaml` is not being used, as the installation step retrieves all packages again: 
```
> opam install . --deps-only
  shell: /usr/bin/bash -e {0}
  env:
    OPAMCOLOR: always
    OPAMCONFIRMLEVEL: unsafe-yes
    OPAMDOWNLOADJOBS: 2
    OPAMERRLOGLEN: 0
    OPAMPRECISETRACKING: 1
    OPAMROOT: /home/runner/.opam
    OPAMYES: 1
    CLICOLOR_FORCE: 1
[mapmap.dev] synchronised (git+file:///home/runner/work/mapmap/mapmap#main)
The following actions will be performed:
=== install 1[3](https://github.com/rusty-key/mapmap/actions/runs/10132831494/job/28017255560#step:5:3)2 packages
  ∗ angstrom                0.16.0       [required by multipart_form, caqti, dream-httpaf, multipart_form-lwt]
  ∗ astring                 0.8.[5](https://github.com/rusty-key/mapmap/actions/runs/10132831494/job/28017255560#step:5:5)        [required by ocaml-lsp-server]
  ∗ base                    v0.1[6](https://github.com/rusty-key/mapmap/actions/runs/10132831494/job/28017255560#step:5:6).3      [required by ocaml-lsp-server, ppx_rapper]
  ∗ base-bytes              base         [required by PostgreSQL]
<...>
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved angstrom.0.16.0  (https://github.com/inhabitedtype/angstrom/archive/0.16.0.tar.gz)
⬇ retrieved base.v0.16.3  (https://github.com/janestreet/base/archive/refs/tags/v0.16.3.tar.gz)
⬇ retrieved astring.0.8.5  (https://erratique.ch/software/astring/releases/astring-0.8.5.tbz)
⬇ retrieved base64.3.5.1  (https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz)
<...>
```

So make question is: how is it supposed to work and how/when it caches opam? My configuration looks like this: 
```
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v3.0.0
      with:
        ocaml-compiler: "5.1.1"
        opam-repositories: |
          default: git+https://github.com/ocaml/opam-repository.git
          andreypopp: git+https://github.com/andreypopp/opam-repository.git
```
↓
```
Run ocaml/setup-ocaml@v3.0.0
  with:
    ocaml-compiler: 5.1.1
    opam-repositories: default: git+https://github.com/ocaml/opam-repository.git
  andreypopp: git+https://github.com/andreypopp/opam-repository.git
  
    allow-prerelease-opam: false
    opam-pin: true
    opam-local-packages: *.opam
    opam-disable-sandboxing: false
    dune-cache: false
    cache-prefix: v1
    github-token: ***
```

Let me know if this is not enough info, I will create a repo with minimal repro

**Comment by smorimoto** [comment]
@rusty-key This happens very rarely, but often depends on the priority and content of the repository. I suspect the solution is to change the order of the repositories, swap priorities, 

```yml
- name: Set-up OCaml
  uses: ocaml/setup-ocaml@v3
  with:
    ocaml-compiler: 5
    opam-repositories: |
      andreypopp: git+https://github.com/andreypopp/opam-repository.git
      default: git+https://github.com/ocaml/opam-repository.git
```

and blow all the cache with the following command: `gh cache delete --all`
