### ISSUE TITLE
Windows: "ERROR while compiling opam-depext.1.2.3"

### ISSUE THREAD

**Issue by nmote** [ocaml/setup-ocaml#850]
[opam-depext](https://opam.ocaml.org/packages/opam-depext/) 1.2.3 was released today. Since then, we have been consistently encountering failures when using this action on Windows. Here's the beginning of our GitHub Actions config:

```
jobs:
  job:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14"
          opam-local-packages: dont_install_local_packages.opam
          opam-repositories: |
            opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            default: https://github.com/ocaml/opam-repository.git
```

And here is an excerpt of the log failure from the `setup-ocaml` step:

```
sh -ex shell/build.sh
+ ocamlc -I src_ext/lib unix.cma cmdliner.cma -o opam-depext $'depext.ml\r'
don't know what to do with depext.ml
Usage: ocamlc <options> <files>
Try 'ocamlc --help' for more information.
  -a  Build a library
  -alert <list>  Enable or disable alerts according to <list>:
        +<alertname>  enable alert <alertname>
        -<alertname>  disable alert <alertname>
        ++<alertname> treat <alertname> as fatal error
        --<alertname> treat <alertname> as non-fatal
        @<alertname>  enable <alertname> and treat it as fatal error
    <alertname> can be 'all' to refer to all alert names
```

Perhaps this action could pin to the previous version of `opam-depext` until this is resolved?
