### ISSUE TITLE
v3 is 2x slower than v2 (at least on Windows)

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#865]
https://github.com/JasonGross/test/actions/runs/10953316111/job/30413386004

```yaml
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.13.1
```
takes 3m39s, while
```yaml
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.13.1
```
takes 8m42s

[logs_28625164728.zip](https://github.com/user-attachments/files/17069974/logs_28625164728.zip)

<details><summary>Full yml file</summary>

```yaml
name: Example Workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    name: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.13.1
    - run: opam exec -- chmod +x test.sh
    - run: opam exec -- cat test.sh
    - run: opam exec -- ./test.sh


  buildv2:

    runs-on: windows-latest
    name: buildv2
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.13.1
    - run: opam exec -- chmod +x test.sh
    - run: opam exec -- cat test.sh
    - run: opam exec -- ./test.sh
```
</details>
